<?php
return array(
	'label' => 'Legal',
	'icon' => 'LG',
	'defaults' => array(
		'company' => get_bloginfo( 'name' ),
		'address' => '',
		'legal_text' => 'You are receiving this email because you subscribed or interacted with our brand.',
		'manage_url' => '',
		'manage_label' => 'Manage your subscription',
		'view_url' => '{VIEW_LINK}',
		'view_label' => 'View online',
		'unsubscribe_url' => '{UNSUBSCRIBE_URL}',
		'unsubscribe_label' => 'Unsubscribe',
		'align' => 'center',
		'background' => '#f8fafc',
		'text_color' => '#64748b',
		'link_color' => '#2563eb',
	),
	'fields' => array(
		array( 'key' => 'company', 'label' => 'Firma', 'type' => 'text' ),
		array( 'key' => 'address', 'label' => 'Adresse', 'type' => 'textarea' ),
		array( 'key' => 'legal_text', 'label' => 'Rechtstext', 'type' => 'textarea' ),
		array( 'key' => 'manage_url', 'label' => 'Manage URL', 'type' => 'text' ),
		array( 'key' => 'manage_label', 'label' => 'Manage Label', 'type' => 'text' ),
		array( 'key' => 'view_url', 'label' => 'View URL', 'type' => 'text' ),
		array( 'key' => 'view_label', 'label' => 'View Label', 'type' => 'text' ),
		array( 'key' => 'unsubscribe_url', 'label' => 'Unsubscribe URL', 'type' => 'text' ),
		array( 'key' => 'unsubscribe_label', 'label' => 'Unsubscribe Label', 'type' => 'text' ),
		array(
			'key' => 'align',
			'label' => 'Ausrichtung',
			'type' => 'select',
			'options' => array(
				array( 'value' => 'left', 'label' => 'Links' ),
				array( 'value' => 'center', 'label' => 'Zentriert' ),
				array( 'value' => 'right', 'label' => 'Rechts' ),
			),
		),
		array( 'key' => 'background', 'label' => 'Hintergrund', 'type' => 'color' ),
		array( 'key' => 'text_color', 'label' => 'Textfarbe', 'type' => 'color' ),
		array( 'key' => 'link_color', 'label' => 'Linkfarbe', 'type' => 'color' ),
	),
);